### ISSUE TITLE
HyperGraphQL

### ISSUE THREAD

**Issue by nicolasfor** [oeg-upm/morph-graphql#144]
It would be good to see a HyperGraphQL example using JSON-LD.

**Comment by dachafra** [comment]
Our aim is not querying RDF as HyperGraphQL is doing (translating GraphQL + context to SPARQL queries). This engine is focused on the automatic creation of GraphQL resolvers to query legacy data (RDB atm) using R2RML, hence, ensuring the use of shared and common vocabularies (or ontologies) of this query interfaces. At this moment we are removing the prefix of the types and fields but they are coming from schema.org. For these reasons, we think that this issue is out of the scope of this approach atm
